import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireTeacherContext } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const sendSchema = z.object({
  report_id: z.string().uuid(),
  email: z.string().email().optional(),
});

export const dynamic = "force-dynamic";

function buildHtml(studentName: string, subject: string, content: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f6f9; }
    .wrapper { max-width: 680px; margin: 0 auto; }
    .header { background: #2563eb; color: #ffffff; padding: 32px 40px; text-align: center; }
    .header h1 { margin: 0; font-size: 22px; font-weight: 700; letter-spacing: 0.5px; }
    .header p  { margin: 6px 0 0; font-size: 13px; opacity: 0.85; }
    .card { background: #ffffff; margin: 24px 16px; border-radius: 12px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); overflow: hidden; }
    .card-body { padding: 32px; }
    .student-info { display: flex; flex-wrap: wrap; gap: 12px 24px; margin-bottom: 24px; padding-bottom: 20px; border-bottom: 1px solid #e5e7eb; }
    .info-item { display: inline-flex; flex-direction: column; }
    .info-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.8px; color: #6b7280; }
    .info-value { font-size: 16px; font-weight: 600; color: #1f2937; }
    .report-content { white-space: pre-line; line-height: 1.75; font-size: 15px; color: #374151; white-space: pre-wrap; }
    .footer { text-align: center; font-size: 12px; color: #9ca3af; padding: 20px 0 28px; }
    .badge { display: inline-block; background: #dbeafe; color: #1d4ed8; border-radius: 9999px; padding: 3px 12px; font-size: 12px; font-weight: 600; letter-spacing: 0.5px; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>EduPulse AI &mdash; Student Progress Report</h1>
      <p>Generated by your trusted tuition companion</p>
    </div>
    <div class="card">
      <div class="card-body">
        <div class="student-info">
          <div class="info-item">
            <span class="info-label">Student</span>
            <span class="info-value">${studentName}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Subject</span>
            <span class="info-value">${subject}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Report Status</span>
            <span class="badge">Progress Report</span>
          </div>
        </div>
        <div class="report-content">${content}</div>
      </div>
    </div>
    <div class="footer">
      <p>This report was generated by EduPulse AI for CBSE private tutors.</p>
      <p style="margin-top:4px;">Questions? Reply to this email to reach your tutor.</p>
    </div>
  </div>
</body>
</html>`;
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const parsed = sendSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid request body", details: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const { report_id, email: providedEmail } = parsed.data;

    const context = await requireTeacherContext();
    if (!context.configured || !context.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const supabase = createSupabaseServerClient();

    const { data: report, error: reportError } = await supabase
      .from("reports")
      .select("id, content, status, subject, sent_to, student_id")
      .eq("id", report_id)
      .maybeSingle();

    if (reportError || !report) {
      return NextResponse.json({ error: "Report not found" }, { status: 404 });
    }

    const { data: student, error: studentError } = await supabase
      .from("students")
      .select("name, teacher_id")
      .eq("id", report.student_id)
      .maybeSingle<{ name: string; teacher_id: string }>();

    if (studentError || !student) {
      return NextResponse.json({ error: "Student not found" }, { status: 404 });
    }

    if (student.teacher_id !== context.user.id) {
      return NextResponse.json(
        { error: "Forbidden: report does not belong to this teacher" },
        { status: 403 }
      );
    }

    const recipient = providedEmail ?? report.sent_to?.[0] ?? null;

    if (!recipient) {
      return NextResponse.json(
        { error: "No recipient email provided and report has no sent_to value" },
        { status: 400 }
      );
    }

    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) {
      return NextResponse.json(
        { error: "Resend API key is not configured" },
        { status: 500 }
      );
    }

    const htmlContent = buildHtml(student.name, report.subject ?? "General", report.content);

    try {
      const resendResponse = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${resendKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: "EduPulse AI <reports@edupulse.ai>",
          to: [recipient],
          subject: `Progress Report: ${student.name} - ${report.subject ?? "General"}`,
          html: htmlContent,
        }),
      });

      if (!resendResponse.ok) {
        const errorText = await resendResponse.text();
        console.error("Resend API error:", resendResponse.status, errorText);

        await supabase
          .from("reports")
          .update({ status: "failed" })
          .eq("id", report_id);

        return NextResponse.json(
          { success: false, error: "Failed to send email via Resend", details: errorText },
          { status: 500 }
        );
      }
    } catch (sendErr) {
      console.error("Resend API call failed:", sendErr);

      await supabase
        .from("reports")
        .update({ status: "failed" })
        .eq("id", report_id);

      return NextResponse.json(
        { success: false, error: "Unable to reach Resend API", details: (sendErr as Error).message },
        { status: 500 }
      );
    }

    const now = new Date().toISOString();
    const { error: updateError } = await supabase
      .from("reports")
      .update({ status: "sent", sent_at: now, sent_to: recipient ? [recipient] : [] })
      .eq("id", report_id);

    if (updateError) {
      console.error("Failed to update report status:", updateError);
    }

    revalidatePath("/app/reports");

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (err) {
    console.error("Unhandled error in report send:", err);
    return NextResponse.json(
      { error: "Internal server error", details: (err as Error).message },
      { status: 500 }
    );
  }
}
